/**
 * Game Center Leaderboard
 * Implementation recruitment task from VirtusLab - internship 2021 Frontend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddResult } from './addResult';


export interface ModelError { 
    target?: object;
    property?: string;
    constrains?: object;
    data?: AddResult;
}

