/**
 * Game Center Leaderboard
 * Implementation recruitment task from VirtusLab - internship 2021 Frontend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Player { 
    id?: string;
    name: string;
}

